

os: Visual Studio 2015

platform:
  - x86
  - x64

init:
  - cmd: "echo JAVA_HOME=%JAVA_HOME%"
  - cmd: "java -version"
  - cmd: "cmake --version"

install:
  - GIT: "submodule update --init --recursive"
  - cinst maven
  - cmd: "echo %M2_HOME%"
  - cmd: "echo %MAVEN_HOME%"
  - mvn "--version"

build_script:
  - cmd: "mvn clean compile test package"