

os: Visual Studio 2015

platform:
  - x86
  - x64

init:
  - "echo JAVA_HOME=%JAVA_HOME%"

install:
  - GIT: "submodule update --init --recursive"

build_script:
  - mvn: "clean compile test package"