/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_bitkings_jbrotli_BrotliStreamCompressor */

#ifndef _Included_de_bitkings_jbrotli_BrotliStreamCompressor
#define _Included_de_bitkings_jbrotli_BrotliStreamCompressor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_bitkings_jbrotli_BrotliStreamCompressor
 * Method:    initJavaFieldIdCache
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_bitkings_jbrotli_BrotliStreamCompressor_initJavaFieldIdCache
  (JNIEnv *, jclass);

/*
 * Class:     de_bitkings_jbrotli_BrotliStreamCompressor
 * Method:    getInputBlockSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_bitkings_jbrotli_BrotliStreamCompressor_getInputBlockSize
  (JNIEnv *, jobject);

/*
 * Class:     de_bitkings_jbrotli_BrotliStreamCompressor
 * Method:    initBrotliCompressor
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_de_bitkings_jbrotli_BrotliStreamCompressor_initBrotliCompressor
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     de_bitkings_jbrotli_BrotliStreamCompressor
 * Method:    compressBytes
 * Signature: ([BII[BI)I
 */
JNIEXPORT jint JNICALL Java_de_bitkings_jbrotli_BrotliStreamCompressor_compressBytes
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     de_bitkings_jbrotli_BrotliStreamCompressor
 * Method:    compressByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;IIZ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_de_bitkings_jbrotli_BrotliStreamCompressor_compressByteBuffer
  (JNIEnv *, jobject, jobject, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
