/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_bitkings_jbrotli_BrotliStreamCompressor */

#ifndef _Included_de_bitkings_jbrotli_BrotliStreamCompressor
#define _Included_de_bitkings_jbrotli_BrotliStreamCompressor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_bitkings_jbrotli_BrotliStreamCompressor
 * Method:    initBrotliCompressor
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_de_bitkings_jbrotli_BrotliStreamCompressor_initBrotliCompressor
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     de_bitkings_jbrotli_BrotliStreamCompressor
 * Method:    compressBytes
 * Signature: (IIII[BII[B)I
 */
JNIEXPORT jint JNICALL Java_de_bitkings_jbrotli_BrotliStreamCompressor_compressBytes
  (JNIEnv *, jobject, jint, jint, jint, jint, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     de_bitkings_jbrotli_BrotliStreamCompressor
 * Method:    compressByteBuffer
 * Signature: (IIIILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_de_bitkings_jbrotli_BrotliStreamCompressor_compressByteBuffer
  (JNIEnv *, jobject, jint, jint, jint, jint, jobject, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
